package pojo;
// Generated 9 dic 2022 14:28:52 by Hibernate Tools 5.5.9.Final

/**
 * Paises generated by hbm2java
 */
public class Paises implements java.io.Serializable {

	private int id;
	private Continentes continentes;
	private String nombre;
	private int poblacion;
	private String jefeEstado;

	public Paises() {
	}

	public Paises(int id, Continentes continentes, String nombre, int poblacion) {
		this.id = id;
		this.continentes = continentes;
		this.nombre = nombre;
		this.poblacion = poblacion;
	}

	public Paises(int id, Continentes continentes, String nombre, int poblacion, String jefeEstado) {
		this.id = id;
		this.continentes = continentes;
		this.nombre = nombre;
		this.poblacion = poblacion;
		this.jefeEstado = jefeEstado;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Continentes getContinentes() {
		return this.continentes;
	}

	public void setContinentes(Continentes continentes) {
		this.continentes = continentes;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(int poblacion) {
		this.poblacion = poblacion;
	}

	public String getJefeEstado() {
		return this.jefeEstado;
	}

	public void setJefeEstado(String jefeEstado) {
		this.jefeEstado = jefeEstado;
	}

}
